### ISSUE TITLE
Running Error: could not find jvm.dll

### ISSUE THREAD

**Issue by alan-el** [raphaelquati/RvJNIHelper#1]
Hi,
I want to call java methods in Qt/C++ and tried this code, but  met difficulties. I cloned this repository and opened it with Qt Creator. After some path configurations in .pro files were modifed, I compiled the code successfully. However, when running it, I got errors printed in console:

Error opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find jvm.dll

My Qt version is 5.14.2 and toolkit is MSVC2017 32bit. In addition, JDK version is 17.

Could someone give me some advice? Thanks in advance.

**Comment by raphaelquati** [comment]
Hi @alan-el,

If you have only Java SDK, there's no key 'Software\JavaSoft\Java Runtime Environment', but 'Software\JavaSoft\JDK'.
The code is not searching for the correct key.
I've migrate the code to Qt6 (at the branch https://github.com/raphaelquati/RvJNIHelper/tree/updateQt6 ), and fixed the code: https://github.com/raphaelquati/RvJNIHelper/blob/170444399f57a16e5e94105cb5d8ce2ab77e6b52/rvjvmhelper/rvjvm.cpp#L86

```c++
#define JDK_KEY	    "Software\\JavaSoft\\JDK"
    
if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, JRE_KEY, 0, KEY_READ, &key) != 0) {
    if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, JDK_KEY, 0, KEY_READ, &key) != 0) {
        fprintf(stderr, "Error opening registry key '%s'\n", JRE_KEY);
        return JNI_FALSE;
    }
}
```

**Comment by alan-el** [comment]
Hello @raphaelquati,
Thank you for your reply, I will try this new code!
